# Generated by Django 5.0.1 on 2024-01-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://alllocal.ca/wp-content/uploads/2020/11/food-placeholder.png', max_length=1000),
        ),
    ]
